language: objective-c
osx_image: xcode8.3
cache:
  - cocoapods: true
  - directories:
    - Carthage

# git:
#   submodules: false

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=RxTextureDataSources.xcworkspace
    - IOS_FRAMEWORK_SCHEME="RxTextureDataSources-iOS"
    - IOS_SDK=iphonesimulator10.2
    - EXAMPLE_SCHEME="Example"
  matrix:
    - DESTINATION="OS=10.2,name=iPhone 7 Plus"              SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"  BUILD_EXAMPLE="YES" RELEASE_READY="YES" POD_LINT="YES"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage update --platform iOS --no-use-binaries --use-submodules --cache-builds
  - pod repo update

before_script:
  # - sh scripts/bootstrap

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
     xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
   fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
     pod lib lint;
   fi

before_deploy:
  # - carthage build --no-skip-current
  # - carthage archive RxTextureDataSources

# deploy:
#   - provider: releases
#     api_key:
#       secure:
#     file:
#       - RxTextureDataSources.framework.zip
#     skip_cleanup: true
#     overwrite: true
#     on:
#       repo: RxSwiftCommunity/RxTextureDataSources
#       tags: true
#       condition: $RELEASE_READY = YES
#   - provider: script
#     script: pod trunk push
#     on:
#       tags: true
#       condition: $RELEASE_READY = YES
